{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emf-gateway.secretName" . }}
  labels:
    {{- include "emf-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ default "" .Values.secrets.redisPassword | quote }}
{{- end }}
