apiVersion: v2
name: emf-ui
description: Helm chart for EMF Admin UI - React-based administration interface
type: application
version: 0.1.0
appVersion: "1.0.0-SNAPSHOT"

keywords:
  - emf
  - ui
  - admin
  - react

home: https://github.com/cklinker/emf
sources:
  - https://github.com/cklinker/emf

maintainers:
  - name: EMF Team

dependencies: []
