{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "emf-worker.fullname" . }}
  labels:
    {{- include "emf-worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "emf-worker.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: {{ .Values.keda.metricsUrl | quote }}
        valueLocation: "unassignedCount"
{{- end }}
