{{- if .Values.config.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emf-gateway.fullname" . }}-redis
  labels:
    {{- include "emf-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.config.redis.password | b64enc | quote }}
{{- end }}
