name: Build Runner Image

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: cklinker

jobs:
  build-runner:
    name: Build & Push Runner Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homelab-argo
        uses: actions/checkout@v4
        with:
          repository: cklinker/homelab-argo
          token: ${{ secrets.ARGOCD_REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: github-runner
          file: github-runner/Dockerfile
          push: true
          tags: |
            cklinker/github-runner-emf:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
